apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  labels:
    app: react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react-container
        image: andrianasolo/react-app:latest  # remplacé par Jenkins (placeholder gardé ci-dessous)
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
  labels:
    app: react
spec:
  selector:
    app: react
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
